source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'FreestarOBJCSample' do  
  # M1 compatible
  pod "FreestarAds", "~> 5.26.0"
  pod "FreestarAds-AdColony", "~> 4.7.2.1"
  pod "FreestarAds-AppLovin", "~> 11.0.0.1"
  pod "FreestarAds-AppLovinMax", "~> 11.0"
  pod "FreestarAds-Criteo", "~> 4.3.1.1"
  pod "FreestarAds-Fyber2", "~> 8.1.6.2"
  pod 'FreestarAds-GAM', '~> 10.0'
  pod 'FreestarAds-GAM/Facebook', '~> 10.0'
  pod 'FreestarAds-Googleadmob', '~> 10.0'
  pod 'FreestarAds-Googleadmob/Facebook', '~> 10.0'
  pod "FreestarAds-Hyprmx", "~> 6.0.3.4"
  pod "FreestarAds-Ogury", "~> 2.1.0.3"
  pod "FreestarAds-Prebid", "~> 2.1.4.12"
  pod "FreestarAds-TAM", "~> 4.6.0.6"
  pod "FreestarAds-Tapjoy", "~> 12.8.0.1"
  pod "FreestarAds-Unity", "~> 4.1.0.4"
  pod "FreestarAds-Yahoo", "~> 1.14.2.2"
  pod "FreestarAds-Nimbus", "~> 2.1.2.4"
  pod "FreestarAds-Smaato", "~> 22.1.3.1"
  
  # Not M1 compatible pods
#  pod "FreestarAds-Vungle", "~> 6.10"
#  pod "FreestarAds-Pangle", "~> 3.7"
  #  pod "FreestarAds-Google", "~> 3.13"

  # helper frameworks for feed view
  pod 'SnapKit', '~> 5.0.0'
  pod 'LoremIpsum', '~> 1.0'

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
