require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'FreestarReactNativeSample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  #  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    # :hermes_enabled => flags[:hermes_enabled],
    # :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FreestarReactNativeSampleTests' do
    inherit! :complete
    # Pods for testing
  end

  versions = {}
  versions['Flipper'] = '~> 0.91.0'
  versions['Flipper-Folly'] = '~> 2.6'
  use_flipper!(versions)

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end


# M1 compatible
pod "FreestarAds-AdColony", "~> 4.7.2.1"
pod "FreestarAds-Tapjoy", "~> 12.8.0.1"
pod "FreestarAds-Criteo", "~> 4.3.1.1"
pod "FreestarAds-AppLovin", "~> 11.0.0.1"
pod "FreestarAds-AppLovinMax", "~> 11.0.0.2"
pod "FreestarAds-Hyprmx", "~> 6.0.0.3"
pod "FreestarAds-Yahoo", "~> 1.14.2.2"
pod "FreestarAds-Ogury", "~> 2.1.0.3"
pod 'FreestarAds-Googleadmob', '~> 9.2.0.3'
pod 'FreestarAds-Googleadmob/Facebook', '~> 9.2.0.3'
pod 'FreestarAds-GAM', '~> 9.2.0.3'
pod 'FreestarAds-GAM/Facebook', '~> 9.2.0.3'
pod "FreestarAds-Unity", "~> 4.1.0.4"
pod "FreestarAds-Prebid", "~> 2.0.0.4"
# pod "FreestarAds-TAM", "~> 4.4.3.3" TAM not Working with ReactNative

# Not M1 compatible pods
pod "FreestarAds-Vungle", "~> 6.10.6.1"
pod "FreestarAds-Nimbus", "~> 1.10.5.1"
pod "FreestarAds-Google", "~> 3.13.0.1"
pod "FreestarAds-Pangle", "~> 3.7.0.1"

end

target 'FreestarReactNativeSample-tvOS' do
  # Pods for FreestarReactNativeSample-tvOS

  target 'FreestarReactNativeSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
