require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'FreestarReactNativeSample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  #  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    # :hermes_enabled => flags[:hermes_enabled],
    # :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'FreestarReactNativeSampleTests' do
    inherit! :complete
    # Pods for testing
  end

  versions = {}
  versions['Flipper'] = '~> 0.91.0'
  versions['Flipper-Folly'] = '~> 2.6'
  use_flipper!(versions)

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

    pod 'FreestarAds-Ogury-PreRelease', '~> 2.1.0.3-beta-6'
    pod 'FreestarAds-AdColony-PreRelease', '~> 4.7.2.2-beta-4'
    pod 'FreestarAds-AppLovin-PreRelease', '~> 11.0.0.2-beta-1'
    pod 'FreestarAds-Googleadmob-PreRelease', '~> 9.2-beta'
    pod 'FreestarAds-Tapjoy-PreRelease', '~> 12.8.0.2-beta-1'
    pod 'FreestarAds-Unity-PreRelease', '~> 4.1.0.4-beta-1'
    pod 'FreestarAds-Vungle-PreRelease', '~> 6.10.6.2-beta-1'
    # pod 'FreestarAds-Google-PreRelease', '~> 2.0.0.3-beta-3'
    pod 'FreestarAds-Criteo-PreRelease', '~> 4.3.1.2-beta-1'
    pod 'FreestarAds-GAM-PreRelease', '~> 9.2.0.3-beta-4'
    pod 'FreestarAds-Nimbus-PreRelease', '~> 1.10.5.2-beta-1'
    # pod 'FreestarAds-TAM-PreRelease', '~> 4.4.3.3-beta-3'

end

target 'FreestarReactNativeSample-tvOS' do
  # Pods for FreestarReactNativeSample-tvOS

  target 'FreestarReactNativeSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
