platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'FreestarReactNativeSample' do
  config = use_native_modules!
  
  use_react_native!(
      :path => config[:reactNativePath],
      # to enable hermes on iOS, change `false` to `true` and then install pods
      :hermes_enabled => false
    )
  
  target 'FreestarReactNativeSampleTests' do
    inherit! :complete
    # Pods for testing
  end
  
  versions = {}
  versions['Flipper'] = '~> 0.91.0'
  versions['Flipper-Folly'] = '~> 2.6'
  use_flipper!(versions)

  post_install do |installer|
    react_native_post_install(installer)
  end
  
  pod 'FreestarAds-AdColony', '~> 4.0'
  pod 'FreestarAds-AppLovin', '~> 4.0'
  pod 'FreestarAds-Googleadmob', '~> 3.0'
  pod 'FreestarAds-Tapjoy', '~> 4.0'
  pod 'FreestarAds-Unity', '~> 5.0'
  pod 'FreestarAds-Vungle', '~> 4.0'
  pod 'FreestarAds-Amazon', '~> 3.0'
  pod 'FreestarAds-Google', '~> 4.0'
  pod 'FreestarAds-Criteo', '~> 2.0'
  pod 'FreestarAds-GAM', '~> 2.0'
  pod 'FreestarAds-Mopub', '~> 4.0'
  pod 'FreestarAds-Nimbus', '~> 2.0'
  pod 'FreestarAds-TAM', '~> 1.0'
  
end

target 'FreestarReactNativeSample-tvOS' do
  # Pods for FreestarReactNativeSample-tvOS

  target 'FreestarReactNativeSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
