source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

target 'FreestarSwiftSample' do

  # M1 compatible
  pod 'FreestarAds-PreRelease', '~> 5.30.0-beta-8'

  pod 'FreestarAds-Prebid-PreRelease', '~> 2.1.5.10-beta-9'
  pod 'FreestarAds-Ogury2-PreRelease', '~> 2.2-beta'
  pod 'FreestarAds-Yahoo-PreRelease', '~> 1.14-beta'
  pod 'FreestarAds-AppLovinMax-PreRelease', '~> 11.11-beta'
  pod 'FreestarAds-AppLovin-PreRelease', '~> 11.11-beta'
  pod 'FreestarAds-AdColony-PreRelease', '~> 4.7-beta'
  pod 'FreestarAds-Tapjoy-PreRelease', '~> 12.8-beta'
  pod 'FreestarAds-Criteo-PreRelease', '~> 4.3-beta'
  pod 'FreestarAds-TAM-PreRelease', '~> 4.7-beta'
  pod 'FreestarAds-Hyprmx-PreRelease', '~> 6.0-beta'
  pod 'FreestarAds-Hyprmx-PreRelease/MRAID', '~> 6.0-beta'
  pod 'FreestarAds-Googleadmob-PreRelease', '~> 10.9.0.8-beta-1'
  pod 'FreestarAds-Googleadmob-PreRelease/Facebook', '~> 10.9.0.8-beta-1'
  pod 'FreestarAds-GAM-PreRelease', '~>  10.9.0.8-beta-1'
  pod 'FreestarAds-GAM-PreRelease/Facebook', '~>  10.9.0.8-beta-1'
  pod 'FreestarAds-Unity-PreRelease', '~> 4.8-beta'
  pod 'FreestarAds-Fyber2-PreRelease', '~> 8.2-beta'
  pod 'FreestarAds-Nimbus-PreRelease', '~> 2.15.0.6-beta'
  pod 'FreestarAds-Smaato-PreRelease', '~> 22.1.3.2-beta-2'
  pod 'FreestarAds-Vungle-PreRelease', '~> 7.0-beta'

#  pod 'Firebase'

#  # Not M1 compatible

#  pod 'FreestarAds-Pangle-PreRelease', '~> 3.7.0.2-beta-2'
  # IMA SDK conflict with Nimbus adapter
#  pod 'FreestarAds-Google-PreRelease', '~> 3.13-beta'

  # helper frameworks for feed view
  pod 'SnapKit', '~> 5.0.0'
  pod 'LoremIpsum', '~> 1.0'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
