# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'FreestarSwiftSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks  
  pod 'FreestarAds', '~> 3.6-alpha'
  pod 'FreestarAds-AdColony', '~> 3.0-alpha'
  pod 'FreestarAds-AppLovin', '~> 3.0-alpha'
  pod 'FreestarAds-Googleadmob', '~> 2.0-alpha'
  pod 'FreestarAds-Tapjoy', '~> 3.0-alpha'
  pod 'FreestarAds-Unity', '~> 4.0-alpha'
  pod 'FreestarAds-Vungle', '~> 3.0-alpha'
  pod 'FreestarAds-Amazon', '~> 2.0-alpha'
  pod 'FreestarAds-Google', '~> 3.0-alpha'
  pod 'FreestarAds-Criteo', '~> 1.0-alpha'
  pod 'FreestarAds-GAM', '~> 1.0-alpha'
  pod 'FreestarAds-Facebook', '~> 3.1-alpha'
  pod 'FreestarAds-Nimbus', '~> 0.1-alpha'
  pod 'Freestar-Nimbus-SDK', '~> 1.7.1'
  
  # helper frameworks for feed view
  pod 'SnapKit', '~> 5.0.0'
  pod 'LoremIpsum', '~> 1.0'
  

end
