source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'FreestarSwiftSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks  
  pod "FreestarAds", "~> 5.8"
  pod "FreestarAds-AdColony", "~> 5.1"
  pod "FreestarAds-Googleadmob", "~> 6.6"
  pod "FreestarAds-Tapjoy", "~> 5.0"
  pod "FreestarAds-Unity", "~> 6.0"
  pod "FreestarAds-Vungle", "~> 5.2"
  pod "FreestarAds-Google", "~> 5.0"
  pod "FreestarAds-Criteo", "~> 3.0"
  pod "FreestarAds-GAM", "~> 5.6"
  pod "FreestarAds-Nimbus", "~> 3.6"
  pod "FreestarAds-Mopub", "~> 5.3"
  pod "FreestarAds-AppLovin", "~> 5.3"
  pod "FreestarAds-AppLovinMax", "~> 11.0.0"
  pod "FreestarAds-TAM", "~> 2.4"
  pod "FreestarAds-Pangle", "~> 1.1"
  pod "FreestarAds-Hyprmx", "~> 6.0.0"

  # helper frameworks for feed view
  pod 'SnapKit', '~> 5.0.0'
  pod 'LoremIpsum', '~> 1.0'

end
